general:
 # export ON_K8S: true
  #buildTool: 'mta'
  #gitSshKeyCredentialsId: 'Sbasu'
  #productiveBranch: 'master'
  #verbose: true
#  jenkinsKubernetes/inheritFrom: true
 # jenkinsKubernetes/jnlpAgent: true
  #jenkinsKubernetes/namespace: true
  #script: this

  #step:
    
   #   buildExecute:
    #    buildTool: 'mta'
     #   npmInstall: true
steps:
   mtaBuild:
    buildTarget: 'CF'
   cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'Sbasu'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      org: '352294e9trial'
      space: 'dev'
