general:
  buildTool: 'mta'
  gitSshKeyCredentialsId: 'Sbasu'
  productiveBranch: 'master'
  verbose: true
  script: this

  step:
  commonPipelineEnvironment:
  
      buildExecute:
        buildTool: 'mta'
        npmInstall: true
   
